# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ar-sybase-jdbc-adapter}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["arkadiy kraportov"]
  s.date = %q{2011-01-13}
  s.description = %q{Adds support for limit and offset for Sybase ASE DB to activerecord-jdbc-adapter for Rails 3}
  s.email = %q{arkadiyk@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "lib/ar-sybase-jdbc-adapter.rb",
    "lib/arel/visitors/sybase_jtds.rb",
    "lib/arjdbc/discover.rb",
    "lib/arjdbc/sybase/sybase_adapter_java.jar",
    "lib/arjdbc/sybase_jtds.rb"
  ]
  s.homepage = %q{http://github.com/arkadiyk/ar-sybase-jdbc-adapter}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Adds support for limit and offset for Sybase JDBC driver}
  s.test_files = [
    "test/helper.rb",
    "test/support/fake_record.rb",
    "test/test_connection.rb",
    "test/test_visitor.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<arel>, ["> 2.0.0"])
      s.add_development_dependency(%q<activerecord-jdbc-adapter>, [">= 1.1.0"])
      s.add_development_dependency(%q<activerecord>, [">= 3.0.3"])
      s.add_runtime_dependency(%q<activerecord-jdbc-adapter>, [">= 1.1.0"])
      s.add_runtime_dependency(%q<arel>, [">= 2.0.6"])
      s.add_runtime_dependency(%q<jdbc-jtds>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 2.0.0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<arel>, ["> 2.0.0"])
      s.add_dependency(%q<activerecord-jdbc-adapter>, [">= 1.1.0"])
      s.add_dependency(%q<activerecord>, [">= 3.0.3"])
      s.add_dependency(%q<activerecord-jdbc-adapter>, [">= 1.1.0"])
      s.add_dependency(%q<arel>, [">= 2.0.6"])
      s.add_dependency(%q<jdbc-jtds>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<arel>, ["> 2.0.0"])
    s.add_dependency(%q<activerecord-jdbc-adapter>, [">= 1.1.0"])
    s.add_dependency(%q<activerecord>, [">= 3.0.3"])
    s.add_dependency(%q<activerecord-jdbc-adapter>, [">= 1.1.0"])
    s.add_dependency(%q<arel>, [">= 2.0.6"])
    s.add_dependency(%q<jdbc-jtds>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 2.0.0"])
  end
end

